services:

  nginx:
    ports:
      - "80:80"

    networks:
      - proxy
      - internal
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - fastapi
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-calorie.rule=Host(`calorie.wenote.me`)"
      - "traefik.http.routers.nginx-calorie.entrypoints=websecure"
      - "traefik.http.services.nginx-calorie.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"

  fastapi:
    networks:
      - internal
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
    expose:
      - "5000"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
  
  redis:
    image: redis:8.6.1-alpine
    restart: always
    networks:
      - internal
    expose:
      - "6379"
    volumes:
      - redis:/data
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"

  rabbitmq:
    image: rabbitmq:4.2.4-management-alpine
    hostname: rabbitmq
    networks:
      - internal
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=CpjvMhAKCC3AHpa8
    expose:
      - "5672"
      - "15672"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  proxy:
    external: true
  internal:
    external: false


volumes:
  redis:
  rabbitmq:
