RABBITMQ_DEFAULT_USER = 'admin'

RABBITMQ_DEFAULT_PASS = 'CpjvMhAKCC3AHpa8'

CELERY_BROKER_URL = 'amqp://' + RABBITMQ_DEFAULT_USER + ':' + RABBITMQ_DEFAULT_PASS + '@rabbitmq:5672'

CELERY_RESULT_BACKEND = 'rpc://'